### ISSUE TITLE
Instructions for Training

### ISSUE THREAD

**Issue by namithap10** [zhaominyiz/RFDA-PyTorch#3]
Hello,

Thank you for releasing the training code. Could you please provide the instructions for training? 

I tried to use the instructions for training [STDF](https://github.com/ryanxingql/stdf-pytorch) - `python -m torch.distributed.launch train_rf_ft.py --opt_path config/Final_QP37.yml` and ran into an error with the STDF module's [in_conv](https://github.com/zhaominyiz/RFDA-PyTorch/blob/ba042bfdc6d9927620b76b1457ef9e0118cd1d59/net_rfda.py#L92) layer:
`Expected 4-dimensional input for 4-dimensional weight [32, 7, 3, 3], but got 5-dimensional input of size [8, 15, 1, 96, 96] instead`
Could you please tell me what radius should be specified in the config file for training? The currently released config file specifies a radius of 7 but from the error log, it seems the training code expects R=3.

Additionally, your paper mentions two-stage training where you train the STDF with radius 3 and then the full network with 15 frame clips. Does your training code support doing that? 

Thank you!

**Comment by zhaominyiz** [comment]
Thanks for the mentioned issue.
This training code is the code of BRF variant which is mentioned in the homepage (0.1 PSNR improvements but with much lower params and faster inference speed). I confused the codes of both of them. I will fix the bug soon. The two-stage training can be easily achieved via modifying the config (change the QE network).
Thank you!

**Comment by zhaominyiz** [comment]
I have uploaded the new training code, see train_rfda_ft.py, and check the differences in line 424.

**Comment by namithap10** [comment]
Hi thank you, could you please also upload the code for the RTVQE module that is used in train_rfda_ft and confirm whether the currently uploaded config file should be used for training with this script?

**Comment by zhaominyiz** [comment]
Done.

**Comment by namithap10** [comment]
Thank you!
