### ISSUE TITLE
关于brf的问题

### ISSUE THREAD

**Issue by woaicv** [zhaominyiz/RFDA-PyTorch#4]
您好，非常感谢您的工作！您的brf版本我看到又有改进，但是代码是不是还没开源？您的这个改进版本工作是不是准备发论文的？期待您的回复，非常感谢！

**Comment by zhaominyiz** [comment]
brf的训练已经给出来了。明天我吧他的model也给出来。他的指标是sota。但是我认为这些创新不足以发文章，因此展示不打算投稿。只可能作为一个baseline。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月24日(周四) 晚上8:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zhaominyiz/RFDA-PyTorch] 关于brf的问题 (Issue #4)




 
您好，非常感谢您的工作！您的brf版本我看到又有改进，但是代码是不是还没开源？您的这个改进版本工作是不是准备发论文的？期待您的回复，非常感谢！

**Comment by woaicv** [comment]
好的，非常感谢您，我现在研一，刚转到这个方向，看到您的工作的指标sota，所以想来学习一下。非常感谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月24日(星期四) 晚上8:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhaominyiz/RFDA-PyTorch] 关于brf的问题 (Issue #4)





 brf的训练已经给出来了。明天我吧他的model也给出来。他的指标是sota。但是我认为这些创新不足以发文章，因此展示不打算投稿。只可能作为一个baseline。 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2022年3月24日(周四) 晚上8:53 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: [zhaominyiz/RFDA-PyTorch] 关于brf的问题 (Issue #4) 
 
 
 
 
   
 您好，非常感谢您的工作！您的brf版本我看到又有改进，但是代码是不是还没开源？您的这个改进版本工作是不是准备发论文的？期待您的回复，非常感谢！

**Comment by woaicv** [comment]
您好，我看到您的cvprw的一篇工作在qp37的情况下psnr已经达到了1.03，而且和stdf的qe模块的flops差不多，是不是说明您在cvprw里设计的模块比您在RFDA里的dsta注意力模块更有效？

**Comment by zhaominyiz** [comment]
不，CVPRW工作的Params和FPS超过了RFDA。

**Comment by woaicv** [comment]
方便问一下psnr 1.03的那个模型参数量和flops fps 大概是多少嘛？感谢🙏

**Comment by zhaominyiz** [comment]
CVPRW的工作使用3090测试的Params和FPS为下：

**Comment by zhaominyiz** [comment]
Params 3074; 240P 23.39; 480P 7.95; 720P 3.59; 1080P 1.61

**Comment by woaicv** [comment]
谢谢您，现在还不太懂压缩，还有点问题就是为什么我用LDP模式QP37解压出来的视频没有明显的块伪影了，就是CU边界不连续的现象看不太出来。

**Comment by zhaominyiz** [comment]
你的QP42也不明显吗？可能是你压缩坏了。MFQE2.0数据集的5个QP太大了，我没有办法向你提供lmdb。请保证你算出来的原始PSNR是一致的。

**Comment by woaicv** [comment]
好的，感谢您的回复，我再检查下。

**Comment by woaicv** [comment]
您好，非常不好意思又打扰您，我想请教一下PVD SD是如何计算的，有没有相关的代码？非常感谢🙏

**Comment by woaicv** [comment]
我试着算了下HEVC的，结果和您的差不多。应该没啥问题，感谢

**Comment by zhaominyiz** [comment]
由于服务器迁移，我不幸搞丢了checkpoint和训练日志。
