### ISSUE TITLE
关于消融实验的问题

### ISSUE THREAD

**Issue by woaicv** [zhaominyiz/RFDA-PyTorch#5]
您好，非常感谢您的工作。我在看您的论文的消融实验时我有些疑惑，为什么只加RF模块，指标甚至比不加的效果还要差，这是什么原因？只加dsta，指标好像已经很高了，即便又多加了RF和two-stage，psnr只有0.02的提升。如果用RF和DSTA，是不是two-stage就没那么重要了，我看表中并没有列出RF和DSTA的组合结果，期待您的解答，非常感谢🙏
![1CDD3762-11EE-4843-8EE7-A1FBB4985FF4](https://user-images.githubusercontent.com/90394190/160333128-8e7f434e-370c-4eae-ad8c-25e4aaaf83ae.png)

**Comment by zhaominyiz** [comment]
Q1：
Two-Stage是为了RF而设计的。只加RF的训练太容易训崩了，因此性能并不理想，所以要使用一些特殊的训练手段。
Q2:
是的，只加DSTA已经可以取得比较好的性能了，这也证明了DSTA的性能。
Q3:
正如前文所述，Two-Stage是为了RF设计的。因此在消融的时候从简考虑。

**Comment by woaicv** [comment]
好的，非常感谢您的回答。我现在尝试跑下您的rfda的代码。我的水平不太行，所以现在有点问题想请教下您。我看到您的代码train_rfda_ft.py好像提供的是第二个阶段的训练，把rf加入，总的迭代次数仅有100000。我看到您的论文里写的第一阶段好像是没有rf的，第一阶段的训练的参数具体是什么，这里没太弄清楚。而且您的create_lmdb_mfqe_rf里radius设置的是0，这里没问题的是嘛？非常感谢🙏

**Comment by zhaominyiz** [comment]
Q1:
第一阶段是为了给STDF和DSTAblocks一个初始状态。
Q2:
radius设置为0是为了将全部的帧做进lmdb，方便后面选取不同的R（如3，7）。这种方法虽然会消耗不少的空间存储，但也更加灵活。

**Comment by woaicv** [comment]
好的，非常感谢您的回复，那么我第一阶段可以按照stdf设置的迭代次数训练一个初始状态，第二阶段加入rf，调用第一阶段的权重进行微调是吧。非常感谢🙏

**Comment by zhaominyiz** [comment]
是的。这里还有一些tricks。即第二阶段只训RF，第三阶段接入STDF、DSTAblocks和RF，并对RF开较小的学习率似乎可以把指标再提一点。这是我后期的一些发现，希望能对你有帮助，祝你科研顺利。

**Comment by woaicv** [comment]
好的，非常感谢您🙏
