### ISSUE TITLE
关于率失真曲线的问题

### ISSUE THREAD

**Issue by woaicv** [zhaominyiz/RFDA-PyTorch#6]
您好，我不太懂视频压缩。对您论文里的率失真曲线不太懂。我看您是取了测试集里的十八个视频中的一个，但是您的这个比特率是怎么算出来的？是根据不同的qp设置，得到的几个值吗？如果是这样，那您用的是1s多少帧，这个是不是涉及到和传输相关的码率控制的问题？即便是固定qp，比特率也会受别的影响吧，不同的图片编码出来的比特数也不一致吧？期待您的回复，万分感谢！🙏

**Comment by zhaominyiz** [comment]
是的。横轴对应5种QP压缩后的视频。你可以通过各种方式去获得比特率。

**Comment by woaicv** [comment]
好的，非常感谢您的答复
