### ISSUE TITLE
bash build.sh is not workinh

### ISSUE THREAD

**Issue by purna821** [zhaominyiz/RFDA-PyTorch#7]
I am trying to run the code by following the instructions
error: '/usr/local/cuda/bin/nvcc' failed: No such file or directory: '/usr/local/cuda/bin/nvcc'

Please help me

**Comment by zhaominyiz** [comment]
The DCN does is hard to build. You may downgrade your pytorch and CUDA version. If you still find difficulty in solving this problem, you may replace the DCN with the implementation of torchvison:

**Comment by zhaominyiz** [comment]
https://pytorch.org/vision/main/generated/torchvision.ops.deform_conv2d.html

**Comment by zhaominyiz** [comment]
Is the trouble solved? :)
