### ISSUE TITLE
How to achieve the two-stage training strategy?

### ISSUE THREAD

**Issue by StevenTony611** [zhaominyiz/RFDA-PyTorch#8]
In your paper, you train the RFDA using the two-stage training strategy, but we can not find the two stage training files in the release code. So we are very confused that how to achieve the two-stage training strategy. Could you provide the training strategy files in detail? 

Thank you very much!

**Comment by zhaominyiz** [comment]
You may implement it by your own :)

**Comment by zhaominyiz** [comment]
Modify L232 at https://github.com/zhaominyiz/RFDA-PyTorch/blob/main/train_rfda_ft.py
